import tkinter
def fun():
    roll=t1.get()
    name=t2.get()
    a=t3.get()
    b=t4.get()
    c=t5.get()
    d=t6.get()
    print(roll,name,a,b,c,d)
root=tkinter.Tk()
root.geometry('200x150')
t1=tkinter.Entry(root)
t2=tkinter.Entry(root)
t3=tkinter.Entry(root)
t4=tkinter.Entry(root)
t5=tkinter.Entry(root)
t6=tkinter.Entry(root)
b1=tkinter.Button(root,text="Submit",command=fun)
t1.pack()
t2.pack()
t3.pack()
t4.pack()
t5.pack()
t6.pack()
b1.pack()
